#!/bin/sh
# Translate text using rofi.
# Requires: rofi, crow-translate
# ---
# 2019 Yusuf Aktepe <yusuf@yusufaktepe.com>
# https://github.com/yusufaktepe/dotfiles
# ---
# Usage:
#       > source:target text
#             de:en hallo
#       > :target text
#               :es hello world!
#       > !
#         to select and translate from history
#       > !d
#         to select and remove from history
#       > !dd
#         to clear history
#
#   If you leave source empty, it'll identify the source
#   and translate it into :target.
#   If you leave both empty, default variables will be used.
# ---

SOURCE="en"
TARGET="tr"
HIST="$XDG_DATA_HOME/rofi/rofitr_history"

rofi_cmd() { rofi -dmenu -width 60 -yoffset 0 -font "Hack 10" "$@" ;}

[ -n "$*" ] && input="$*" || input="$(rofi_cmd -p " translate" -l 0)"

while [ -n "$input" ]; do
	case "$input" in
		!)	input="$(tac "$HIST" | rofi_cmd -p " history" -l 20)" ;;
		!d)	pattern="$(tac "$HIST" | rofi_cmd -p " delete" -l 20)"
			case "$pattern" in
				!) input="$(rofi_cmd -p " translate" -l 0)" ;;
				!dd) printf '' > "$HIST" && exit 0 ;;
				"") exit 0 ;;
				*) sed -i "/^$pattern$/d" "$HIST"
			esac ;;
		!dd)	printf '' > "$HIST" && input="$(rofi_cmd -p " translate" -l 0)" ;;
		*)
			crow_cmd() {
				case "$input" in
					??:??*)
						SOURCE=$(echo "$input" | awk -F':' '{print $1}')
						TARGET=$(echo "$input" | awk -F'[:| ]' '{print $2}')
						input=$(echo "$input" | cut -d' ' -f2-)
						crow -s "$SOURCE" -t "$TARGET" "$input" ;;
					:??*)
						TARGET=$(echo "$input" | awk -F'[:| ]' '{print $2}')
						input=$(echo "$input" | cut -d' ' -f2-)
						crow -t "$TARGET" "$input" ;;
					*)	crow -s "$SOURCE" -t "$TARGET" "$input" ;;
				esac
			}

			result="$(crow_cmd | sed '/- examples:/Q;/^$/d;s/\&/\&amp\;/g')"
			sed -i "/^$input$/d" "$HIST" && printf '%s\n' "$input" >> "$HIST"
			input="$(rofi_cmd -p " translate" -l 0 -mesg "<span color='#ebdbb2'>$result</span>")"
	esac
done
